/**
 * Local filesystem video provider — development only.
 *
 * Exists so the entire pipeline (upload → asset record → authorization → signed
 * playback → concurrency ledger → player) is runnable and testable without any
 * client-provisioned provider credentials. Bunny is the one piece of the video
 * path that cannot be verified locally, so everything around it needs to be
 * exercisable independently, otherwise a bug anywhere in the chain hides behind
 * "we can't test video yet".
 *
 * Both ends of the token are ours here, so unlike the Bunny signature this is
 * fully verified — see signing.test.ts and the route that consumes it.
 *
 * Refuses to operate in production: it offers no DRM and no real watermarking.
 */

import { mkdir, stat, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'

import {
  MediaProviderError,
  type RemoteAssetState,
  type SignPlaybackInput,
  type SignedPlayback,
  type UploadTarget,
  type VideoProviderAdapter,
} from './types'
import { signLocalToken, unixSeconds } from './signing'

/** Under .next so it is already gitignored and cleared by a clean build. */
const STORAGE_DIR = join(process.cwd(), '.next', 'cache', 'local-media')

const UPLOAD_WINDOW_SEC = 4 * 60 * 60

function assertNotProduction(): void {
  if (process.env.NODE_ENV === 'production') {
    throw new MediaProviderError(
      'The LOCAL video provider cannot be used in production — it provides no DRM and no forensic watermarking. Set integrations.video to a real provider in the brand config.',
    )
  }
}

function signingSecret(): string {
  const secret = process.env.AUTH_SECRET
  if (!secret) {
    throw new MediaProviderError('AUTH_SECRET is required to sign local playback tokens.')
  }
  return secret
}

export function localMediaPath(providerAssetId: string): string {
  // Guard against traversal: ids are generated by us, but this path is joined
  // with user-reachable input in the serving route.
  if (!/^[a-zA-Z0-9_-]+$/.test(providerAssetId)) {
    throw new MediaProviderError(`Invalid local media id "${providerAssetId}".`)
  }
  return join(STORAGE_DIR, providerAssetId)
}

export async function ensureLocalStorage(): Promise<string> {
  await mkdir(STORAGE_DIR, { recursive: true })
  return STORAGE_DIR
}

export const localVideoAdapter: VideoProviderAdapter = {
  key: 'LOCAL',
  name: 'Local filesystem (development)',
  requiredEnv: ['AUTH_SECRET'],
  supportsDrm: false,
  supportsServerWatermark: false,

  async createUploadTarget({ filename }) {
    assertNotProduction()
    await ensureLocalStorage()

    const id = randomUUID()
    const expiresAtUnix = unixSeconds(new Date()) + UPLOAD_WINDOW_SEC

    // The upload is authorised by the same HMAC scheme as playback, with the
    // asset id standing in for the viewer, so an unauthenticated PUT cannot
    // write arbitrary files.
    const token = signLocalToken({
      secret: signingSecret(),
      assetId: id,
      viewerId: 'upload',
      expiresAtUnix,
    })

    const query = new URLSearchParams({ token, expires: String(expiresAtUnix) })

    return {
      url: `/api/media/local/${id}?${query.toString()}`,
      method: 'PUT',
      protocol: 'binary',
      headers: filename ? { 'X-Original-Filename': filename } : undefined,
      providerAssetId: id,
      playbackId: id,
      expiresAt: new Date(expiresAtUnix * 1000),
    } satisfies UploadTarget
  },

  async signPlayback({ asset, viewer, ttlSec }: SignPlaybackInput): Promise<SignedPlayback> {
    assertNotProduction()

    const id = asset.playbackId ?? asset.providerAssetId
    if (!id) throw new MediaProviderError(`Asset ${asset.id} has no local media id.`)

    const expiresAtUnix = unixSeconds(new Date()) + ttlSec
    const token = signLocalToken({
      secret: signingSecret(),
      assetId: id,
      viewerId: viewer.id,
      expiresAtUnix,
    })

    const query = new URLSearchParams({
      token,
      expires: String(expiresAtUnix),
      viewer: viewer.id,
    })

    return {
      // Progressive MP4 rather than HLS: no transcoding pipeline locally.
      url: `/api/media/local/${id}?${query.toString()}`,
      format: 'mp4',
      expiresAt: new Date(expiresAtUnix * 1000),
      thumbnailUrl: null,
    }
  },

  async getAssetState(providerAssetId): Promise<RemoteAssetState> {
    assertNotProduction()
    try {
      const info = await stat(localMediaPath(providerAssetId))
      return {
        status: info.size > 0 ? 'READY' : 'UPLOADING',
        sizeBytes: info.size,
        // No transcoder locally, so duration comes from the client on upload.
        durationSec: null,
        thumbnailUrl: null,
      }
    } catch {
      return { status: 'UPLOADING', sizeBytes: null, durationSec: null }
    }
  },

  async deleteAsset(providerAssetId) {
    assertNotProduction()
    try {
      await unlink(localMediaPath(providerAssetId))
    } catch {
      // Already gone is success.
    }
  },
}
