/**
 * Razorpay webhook payload interpretation.
 *
 * Pure. Turns an untrusted JSON string into either a typed intent this system
 * knows how to act on, or a refusal — nothing in here touches the database, so
 * every shape a gateway can send (including malformed and hostile ones) is
 * testable without a fixture.
 *
 * ── AMOUNTS ──────────────────────────────────────────────────────────────────
 * Razorpay reports `amount` in the currency's minor unit already: 50000 is
 * ₹500.00, not ₹50,000. It is therefore stored verbatim and never multiplied.
 * The one place this could go wrong is a currency with a different exponent, so
 * the currency travels with the amount and reconciliation compares both.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Event types this deployment acts on. Everything else is recorded and ignored. */
const HANDLED_EVENTS = [
  'payment.captured',
  'payment.failed',
  'order.paid',
  'refund.processed',
] as const

export interface ParsedRazorpayEvent {
  /** e.g. "payment.captured" */
  type: string
  payload: Record<string, unknown>
}

export type PaymentIntent =
  | {
      kind: 'PAYMENT_CAPTURED'
      gatewayOrderId: string | null
      gatewayPaymentId: string
      amountMinor: number
      currency: string
      method: string | null
      capturedAt: Date
    }
  | {
      kind: 'PAYMENT_FAILED'
      gatewayOrderId: string | null
      gatewayPaymentId: string
      amountMinor: number
      currency: string
      method: string | null
      reason: string | null
    }
  | {
      kind: 'REFUND_PROCESSED'
      gatewayPaymentId: string
      gatewayRefundId: string
      /** Cumulative amount refunded against the payment, as the gateway sees it. */
      refundedMinor: number
      currency: string
    }
  /** Understood, but nothing for this system to do. */
  | { kind: 'IGNORED'; type: string }
  /** Signed by the right secret but structurally unusable. Worth alerting on. */
  | { kind: 'MALFORMED'; type: string; problem: string }

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function readString(source: Record<string, unknown>, key: string): string | null {
  const value = source[key]
  return typeof value === 'string' && value.length > 0 ? value : null
}

/** Minor units must be a non-negative safe integer; anything else is a bad feed. */
function readMinor(source: Record<string, unknown>, key: string): number | null {
  const value = source[key]
  return typeof value === 'number' && Number.isSafeInteger(value) && value >= 0 ? value : null
}

/** `payload.<name>.entity`, the shape every Razorpay event uses. */
function entity(payload: Record<string, unknown>, name: string): Record<string, unknown> | null {
  const container = payload[name]
  if (!isRecord(container)) return null
  const value = container.entity
  return isRecord(value) ? value : null
}

/**
 * Parses the body. Returns null when it is not a Razorpay event envelope at all,
 * which the caller reports as a 400 rather than recording — an unparseable body
 * that nonetheless carried a valid signature means our secret has leaked or
 * Razorpay changed their envelope, and neither is fixed by a retry.
 */
export function parseRazorpayEvent(rawBody: string): ParsedRazorpayEvent | null {
  let body: unknown
  try {
    body = JSON.parse(rawBody)
  } catch {
    return null
  }

  if (!isRecord(body)) return null

  const type = readString(body, 'event')
  if (!type) return null

  const payload = body.payload
  return { type, payload: isRecord(payload) ? payload : {} }
}

/**
 * Idempotency key for an event.
 *
 * Razorpay sends `x-razorpay-event-id` and that is the right key when present.
 * When it is absent — older accounts, and replays generated by the dashboard's
 * "resend" button — a deterministic composite of the event type and the entity
 * it concerns keeps replays colliding, which is the whole point. A random
 * fallback would defeat the unique constraint that stops double-crediting.
 */
export function razorpayEventKey(
  headerEventId: string | null | undefined,
  parsed: ParsedRazorpayEvent,
): string {
  if (headerEventId) return headerEventId

  const subject =
    readString(entity(parsed.payload, 'refund') ?? {}, 'id') ??
    readString(entity(parsed.payload, 'payment') ?? {}, 'id') ??
    readString(entity(parsed.payload, 'order') ?? {}, 'id') ??
    'unknown'

  return `${parsed.type}:${subject}`
}

function paymentIntent(
  payment: Record<string, unknown>,
  type: string,
  captured: boolean,
): PaymentIntent {
  const gatewayPaymentId = readString(payment, 'id')
  const amountMinor = readMinor(payment, 'amount')
  const currency = readString(payment, 'currency')

  if (!gatewayPaymentId || amountMinor === null || !currency) {
    return { kind: 'MALFORMED', type, problem: 'payment entity is missing id, amount or currency' }
  }

  const gatewayOrderId = readString(payment, 'order_id')
  const method = readString(payment, 'method')

  if (!captured) {
    const errorDescription =
      readString(payment, 'error_description') ?? readString(payment, 'error_code')
    return {
      kind: 'PAYMENT_FAILED',
      gatewayOrderId,
      gatewayPaymentId,
      amountMinor,
      currency,
      method,
      reason: errorDescription,
    }
  }

  // `created_at` is unix seconds. A missing or absurd timestamp falls back to
  // now rather than failing the event: the money moved either way, and refusing
  // to credit an enrollment over a clock field would be the wrong trade.
  const createdAt = payment.created_at
  const capturedAt =
    typeof createdAt === 'number' && Number.isFinite(createdAt) && createdAt > 0
      ? new Date(createdAt * 1000)
      : new Date()

  return {
    kind: 'PAYMENT_CAPTURED',
    gatewayOrderId,
    gatewayPaymentId,
    amountMinor,
    currency,
    method,
    capturedAt,
  }
}

export function interpretRazorpayEvent(parsed: ParsedRazorpayEvent): PaymentIntent {
  if (!(HANDLED_EVENTS as readonly string[]).includes(parsed.type)) {
    return { kind: 'IGNORED', type: parsed.type }
  }

  switch (parsed.type) {
    case 'payment.captured': {
      const payment = entity(parsed.payload, 'payment')
      if (!payment) {
        return { kind: 'MALFORMED', type: parsed.type, problem: 'no payment entity' }
      }
      return paymentIntent(payment, parsed.type, true)
    }

    case 'payment.failed': {
      const payment = entity(parsed.payload, 'payment')
      if (!payment) {
        return { kind: 'MALFORMED', type: parsed.type, problem: 'no payment entity' }
      }
      return paymentIntent(payment, parsed.type, false)
    }

    /**
     * `order.paid` carries the payment entity too, so it settles through the same
     * path. Handling both it and `payment.captured` is deliberate: whichever
     * subscription the client's dashboard ends up with, the enrollment happens.
     * Handling both is only safe because settlement is idempotent — see the
     * compare-and-set in ./orders.ts.
     */
    case 'order.paid': {
      const payment = entity(parsed.payload, 'payment')
      if (!payment) return { kind: 'IGNORED', type: parsed.type }
      return paymentIntent(payment, parsed.type, true)
    }

    case 'refund.processed': {
      const refund = entity(parsed.payload, 'refund')
      if (!refund) {
        return { kind: 'MALFORMED', type: parsed.type, problem: 'no refund entity' }
      }

      const gatewayRefundId = readString(refund, 'id')
      const gatewayPaymentId = readString(refund, 'payment_id')
      const currency = readString(refund, 'currency') ?? 'INR'

      if (!gatewayRefundId || !gatewayPaymentId) {
        return { kind: 'MALFORMED', type: parsed.type, problem: 'refund is missing ids' }
      }

      /**
       * Prefer the payment entity's cumulative `amount_refunded` over this
       * refund's own amount. Two partial refunds against one payment would
       * otherwise each look like the total, and the order would flip to
       * REFUNDED after the first.
       */
      const payment = entity(parsed.payload, 'payment')
      const cumulative = payment ? readMinor(payment, 'amount_refunded') : null
      const own = readMinor(refund, 'amount')

      if (cumulative === null && own === null) {
        return { kind: 'MALFORMED', type: parsed.type, problem: 'refund has no usable amount' }
      }

      return {
        kind: 'REFUND_PROCESSED',
        gatewayPaymentId,
        gatewayRefundId,
        refundedMinor: cumulative ?? own ?? 0,
        currency,
      }
    }

    default:
      return { kind: 'IGNORED', type: parsed.type }
  }
}
